### ISSUE TITLE
Missing file

### ISSUE THREAD

**Issue by kdamon** [rsk22/Arduino-TouchScreenKeypad#1]
I don't see the *.ino file that's to be loaded.

Thanks,
Kyle

**Comment by rsk22** [comment]
I am sorry for the late reply.  I somehow missed your comment.  This is a library that does not need a .ino file.  You can upload the .h and .cpp files to your Arduino library and create your own projects.  If you need an example, I can provide one.  The code comments should be clear though.

**Comment by AllanThomsen** [comment]
I would love a .ini sketch sample to go with library :)

**Comment by AllanThomsen** [comment]
The library is also dependent on a TouchScreenGeometry.h that is not included in the files.

Arduino: 1.6.7 (Windows 10), Board: "Arduino/Genuino Mega or Mega 2560, ATmega2560 (Mega 2560)"

In file included from C:\Users\User\Documents\Arduino\Port_og_alarm_styring\Port_og_alarm_styring.ino:1:0:

C:\Users\User\Documents\Arduino\libraries\Arduino-TouchScreenKeypad-master/TouchScreenKeypad.h:16:33: fatal error: TouchScreenGeometry.h: No such file or directory

 #include <TouchScreenGeometry.h>

compilation terminated.

exit status 1
Error compiling.

**Comment by rsk22** [comment]
That file, TouchScreenGeometry, is included in my Github library.

**Comment by rsk22** [comment]
Also, there is an example file already included in my library: https://github.com/rsk22/Touch_Screen_Keypad/blob/master/TouchScreen_Keypad_Rev_3/TouchScreen_Keypad_Rev_3.ino
